## ============================================================
## 04_DEA_DESeq2.R
## Generic differential expression script using DESeq2, based on
## the quantification matrix generated by featureCounts
## (03_featurecounts.sh).
##
## For each comparison defined in COMPARISONS, generates:
##   1. CSV with all DESeq2 results
##   2. Rank file (.rnk) sorted by log2FC, no headers (for GSEA)
##   3. Unlabeled volcano plot
##   4. Volcano plot with the top N most significant genes labeled
##   5. Heatmap of significant genes (up + down)
##   6. Separate CSVs of upregulated and downregulated genes
##
## Also saves normalized matrices (counts and VST) with gene
## symbol instead of Ensembl ID.
## ============================================================

library(DESeq2)
library(AnnotationDbi)
library(ggplot2)
library(ggrepel)
library(pheatmap)

## ============================================================
## 0. CONFIGURATION — edit this section for each project
## ============================================================

# CHANGE: working directory (where the quantification file is located)
setwd("")

# CHANGE: featureCounts output file
counts_file <- "gene_quantification.txt"

# CHANGE: output folder for all results
out_root <- "DEA_results"

# CHANGE: organism annotation package (org.Mm.eg.db for mouse,
# org.Hs.eg.db for human, etc.) — install via BiocManager if needed
library(org.Mm.eg.db)
annotation_db <- org.Mm.eg.db

# CHANGE: column names from the featureCounts file that correspond
# to each BAM sample, and their experimental condition/group. The
# order must exactly match the order of the quantification columns.
# Tip: run colnames(read.table(counts_file, header=TRUE, sep="\t", nrows=1))
# to confirm the order and names before filling this in.
sample_columns <- c(
  # "column_name_in_file" = "condition"
)

# CHANGE: if the experimental design has paired replicates (e.g.
# same animal/passage across different conditions), add a replicate
# vector with the same order as sample_columns and uncomment the
# corresponding design line below.
# replicate <- c("N1", "N1", "N2", "N2", "N3", "N3")

# CHANGE: list of comparisons to run.
# Each element: contrast (treatment, reference) + output folder.
COMPARISONS <- list(
  list(treatment = "CONDITION_A", reference = "CONDITION_B",
       out_dir   = "CONDITION_A_vs_CONDITION_B")
  # Add more comparisons here
)

# Significance thresholds
PADJ_THRESHOLD <- 0.05
LFC_THRESHOLD  <- 0       # use >0 to require a minimum log2FC
TOP_N_LABELS   <- 10      # number of genes labeled in the volcano plot

## ============================================================
## 1. Load count matrix
## ============================================================

raw <- read.table(counts_file, header = TRUE, sep = "\t", comment.char = "#")

# The first 6 columns from featureCounts are metadata
# (Geneid, Chr, Start, End, Strand, Length); the rest are samples.
stopifnot(length(sample_columns) > 0)

counts <- raw[, names(sample_columns)]
rownames(counts) <- raw$Geneid
colnames(counts) <- names(sample_columns)

## ============================================================
## 2. Filter genes with zero counts
## ============================================================

cat("Raw matrix dimensions:", nrow(counts), "genes x", ncol(counts), "samples\n")
counts <- counts[rowSums(counts) > 0, ]
cat("Genes with counts > 0:", nrow(counts), "\n")

## ============================================================
## 3. Convert Ensembl ID to gene symbol
## ============================================================

ensembl_ids <- sub("\\..*", "", rownames(counts))  # strip version if present

symbols <- mapIds(annotation_db,
                  keys      = ensembl_ids,
                  column    = "SYMBOL",
                  keytype   = "ENSEMBL",
                  multiVals = "first")

gene_names       <- ifelse(is.na(symbols), ensembl_ids, symbols)
gene_names       <- make.unique(gene_names)
rownames(counts) <- gene_names

## ============================================================
## 4. Sample metadata
## ============================================================

col_data <- data.frame(
  sample    = colnames(counts),
  condition = factor(unname(sample_columns)),
  row.names = colnames(counts)
)

# If a replicate vector was defined, uncomment:
# col_data$replicate <- factor(replicate)
# DESIGN <- ~ replicate + condition
DESIGN <- ~ condition

cat("\nSample metadata:\n")
print(col_data)

## ============================================================
## 5. Global PCA + normalized matrices
## ============================================================

dir.create(out_root, showWarnings = FALSE)
dir.create(file.path(out_root, "PCA"), showWarnings = FALSE, recursive = TRUE)

dds_all <- DESeqDataSetFromMatrix(countData = counts,
                                  colData   = col_data,
                                  design    = DESIGN)
dds_all <- estimateSizeFactors(dds_all)
vsd_all <- vst(dds_all, blind = TRUE)

pca_data <- plotPCA(vsd_all, intgroup = "condition", returnData = TRUE)
pct_var  <- round(100 * attr(pca_data, "percentVar"), 1)

p_pca <- ggplot(pca_data, aes(x = PC1, y = PC2, color = condition, label = name)) +
  geom_point(size = 4) +
  geom_text_repel(size = 3) +
  xlab(paste0("PC1: ", pct_var[1], "% variance")) +
  ylab(paste0("PC2: ", pct_var[2], "% variance")) +
  theme_bw() +
  ggtitle("Global PCA")

ggsave(file.path(out_root, "PCA", "PCA_global.png"),
       p_pca, width = 8, height = 6, dpi = 300)

norm_counts <- counts(dds_all, normalized = TRUE)
write.csv(as.data.frame(norm_counts),
          file = file.path(out_root, "normalized_counts.csv"))

vst_matrix <- assay(vsd_all)
write.csv(as.data.frame(vst_matrix),
          file = file.path(out_root, "VST_matrix.csv"))

cat("PCA and normalized matrices saved in", out_root, "\n")

## ============================================================
## 6. DEA function + per-comparison outputs
## ============================================================

run_dea <- function(counts_sub, col_data_sub, contrast, out_dir,
                    lfc_threshold = LFC_THRESHOLD,
                    padj_threshold = PADJ_THRESHOLD,
                    top_n = TOP_N_LABELS) {

  dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

  dds <- DESeqDataSetFromMatrix(countData = counts_sub,
                                colData   = col_data_sub,
                                design    = DESIGN)
  dds$condition <- relevel(dds$condition, ref = contrast[3])
  dds <- DESeq(dds)
  res <- results(dds, contrast = contrast, alpha = padj_threshold)

  # lfcShrink requires the 'ashr' package (install.packages("ashr"))
  res <- lfcShrink(dds, contrast = contrast, res = res, type = "ashr")

  res_df      <- as.data.frame(res)
  res_df$gene <- rownames(res_df)
  res_df      <- res_df[order(res_df$padj, na.last = TRUE), ]

  # ── 1. CSV with all results ──────────────────────────────────────
  write.csv(res_df,
            file      = file.path(out_dir, "DESeq2_results_all.csv"),
            row.names = FALSE)

  # ── 2. Rank file for GSEA ────────────────────────────────────────────────
  rank_df <- res_df[!is.na(res_df$log2FoldChange), c("gene", "log2FoldChange")]
  rank_df <- rank_df[order(rank_df$log2FoldChange, decreasing = TRUE), ]
  write.table(rank_df,
              file      = file.path(out_dir, "GSEA_ranked.rnk"),
              sep       = "\t",
              row.names = FALSE,
              col.names = FALSE,
              quote     = FALSE)

  # ── 3 & 4. Volcano plots ─────────────────────────────────────────────────
  vol_df     <- res_df[!is.na(res_df$padj) & !is.na(res_df$log2FoldChange), ]
  vol_df$sig <- "NS"
  vol_df$sig[vol_df$padj < padj_threshold & vol_df$log2FoldChange >  lfc_threshold] <- "UP"
  vol_df$sig[vol_df$padj < padj_threshold & vol_df$log2FoldChange < -lfc_threshold] <- "DOWN"
  vol_df$sig <- factor(vol_df$sig, levels = c("UP", "DOWN", "NS"))

  colors_vol <- c("UP" = "#d73027", "DOWN" = "#4575b4", "NS" = "grey70")

  p_vol <- ggplot(vol_df, aes(x = log2FoldChange, y = -log10(padj), color = sig)) +
    geom_point(alpha = 0.5, size = 1.2) +
    scale_color_manual(values = colors_vol) +
    geom_hline(yintercept = -log10(padj_threshold), linetype = "dashed", color = "grey40") +
    theme_bw() +
    labs(title = paste(contrast[2], "vs", contrast[3]),
         x     = "log2 Fold Change",
         y     = "-log10(padj)",
         color = "") +
    theme(legend.position = "top")

  ggsave(file.path(out_dir, "Volcano_unannotated.png"),
         p_vol, width = 7, height = 6, dpi = 300)

  top_genes_label <- vol_df[vol_df$sig != "NS", ]
  top_genes_label <- top_genes_label[order(top_genes_label$padj), ]
  top_genes_label <- top_genes_label[seq_len(min(top_n, nrow(top_genes_label))), ]

  p_vol_ann <- p_vol +
    geom_text_repel(data          = top_genes_label,
                    aes(label     = gene),
                    size          = 3,
                    color         = "black",
                    box.padding   = 0.4,
                    point.padding = 0.3,
                    max.overlaps  = 20)

  ggsave(file.path(out_dir, paste0("Volcano_top", top_n, "annotated.png")),
         p_vol_ann, width = 7, height = 6, dpi = 300)

  # ── 5. Heatmap of significant genes ──────────────────────────────────────
  sig_genes <- res_df$gene[!is.na(res_df$padj) &
                              res_df$padj < padj_threshold &
                              abs(res_df$log2FoldChange) > lfc_threshold]

  if (length(sig_genes) >= 2) {
    vsd <- vst(dds, blind = FALSE)
    mat <- assay(vsd)[sig_genes, , drop = FALSE]
    mat <- mat - rowMeans(mat)

    if (nrow(mat) > 200) {
      top_genes <- res_df$gene[res_df$gene %in% sig_genes][1:200]
      mat       <- mat[top_genes, , drop = FALSE]
    }

    ann_col <- as.data.frame(col_data_sub[, "condition", drop = FALSE])

    pheatmap(mat,
             annotation_col = ann_col,
             show_rownames  = nrow(mat) <= 50,
             cluster_cols   = TRUE,
             cluster_rows   = TRUE,
             fontsize_row   = 7,
             main           = paste("Heatmap -", contrast[2], "vs", contrast[3]),
             filename       = file.path(out_dir, "Heatmap_sig_genes.png"),
             width          = 8,
             height         = 10)
  } else {
    cat("  ⚠ Fewer than 2 significant genes — heatmap skipped\n")
  }

  # ── 6. Up / down CSVs ────────────────────────────────────────────────────
  up_genes   <- res_df[!is.na(res_df$padj) &
                         res_df$padj < padj_threshold &
                         res_df$log2FoldChange > lfc_threshold, ]
  down_genes <- res_df[!is.na(res_df$padj) &
                         res_df$padj < padj_threshold &
                         res_df$log2FoldChange < -lfc_threshold, ]

  write.csv(up_genes,
            file      = file.path(out_dir, "genes_upregulated.csv"),
            row.names = FALSE)
  write.csv(down_genes,
            file      = file.path(out_dir, "genes_downregulated.csv"),
            row.names = FALSE)

  cat(sprintf("  ✓ %s vs %s → UP: %d | DOWN: %d | Total sig: %d\n",
              contrast[2], contrast[3],
              nrow(up_genes), nrow(down_genes),
              nrow(up_genes) + nrow(down_genes)))

  invisible(res_df)
}

## ============================================================
## 7. Run all comparisons defined in COMPARISONS
## ============================================================

for (comp in COMPARISONS) {
  cat(sprintf("\n### Comparison: %s vs %s\n", comp$treatment, comp$reference))

  sel        <- col_data$condition %in% c(comp$treatment, comp$reference)
  counts_sub <- counts[, sel]
  coldat_sub <- col_data[sel, , drop = FALSE]
  coldat_sub$condition <- droplevels(coldat_sub$condition)
  if ("replicate" %in% colnames(coldat_sub)) {
    coldat_sub$replicate <- droplevels(coldat_sub$replicate)
  }

  run_dea(counts_sub, coldat_sub,
          contrast = c("condition", comp$treatment, comp$reference),
          out_dir  = file.path(out_root, comp$out_dir))
}

cat("\n### DEA pipeline complete. Results in:", out_root, "\n")
