#!/bin/bash
#SBATCH --job-name=fCounts
#SBATCH --partition=long
#SBATCH --nodes=1
#SBATCH --output=fCounts_quantification.out
#SBATCH --error=fCounts_quantification.err

# ============================================================
# 03_featurecounts.sh
# Gene-level read quantification with featureCounts, from the
# sorted BAM files generated by STAR.
# ============================================================

# ── Paths to configure ──────────────────────────────────

# CHANGE: project root folder (same as WKD in 02_STAR_alignment.sh)
WKD=""

# CHANGE: project name, used as a prefix for the output file
PROJECT=""

# GTF annotation (mm10 / GRCm38.102) — must match the STAR index version
GTF="/projects/cancer/HelenaBrunel/CELIATON26/Mus_musculus.GRCm38.102.gtf"

# Folder with Singularity images (.sif)
IMAGES_PATH="/projects/cancer/images"

START=$(date +%s)

# Singularity bind path
export SINGULARITY_BIND="/projects/cancer"

DATA="${WKD}/bam_files"
OUT="${WKD}/quantification"
mkdir -p "${OUT}"

# Name of the featureCounts Singularity image
FCOUNTS='featureCounts_subRead_v2.0.1.sif'

# ── Parameters ───────────────────────────────────────────────
T='6'       # threads
ST='2'      # library strandedness: 0=unstranded, 1=forward, 2=reverse
            # CHANGE based on the library kit used (verify with
            # RSeQC's infer_experiment.py if unknown)
ft='exon'   # feature type (-t)
at='gene_id' # attribute type (-g)

# Other relevant parameters (not enabled by default):
#   -p   paired-end only: count fragments instead of reads
#   -C   do NOT count chimeric reads
#   -B   only count read pairs with both ends aligned
#   -M   also count multi-mappers

################################################################################
## Quantification
################################################################################

BAM=$(for f in "$DATA"/*.bam; do printf '%s ' "$f"; done)

echo ''
echo 'Starting read quantification with featureCounts....................... '$(date)
echo ''

singularity exec "$IMAGES_PATH/$FCOUNTS" featureCounts \
  -T "$T" -s "$ST" -t "$ft" -g "$at" -a "$GTF" -p -C -B \
  -o "$OUT/${PROJECT}_gene_quantification.txt" $BAM

END=$(date +%s)
DIFF=$(( END - START ))
echo "Processing time: $DIFF seconds"
